#!/bin/sh
chmod 777 /usr/share/e-sabit
chmod 755 /usr/share/e-sabit/restorebutton.sh
chmod 755 /usr/share/e-sabit/restoreservice.sh
chmod 755 /usr/share/e-sabit/backup.sh

mkdir /var/backups
mkdir /var/backups/e-sabit

systemctl enable e-sabit.service
systemctl start e-sabit.service
systemctl daemon-reload